import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { numberToWords } from './number-to-words';
import type { Bill, User } from './types';

export function generateInvoicePDF(bill: Bill, user: User): void {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = 210;
  const margin = 10;
  const contentWidth = pageWidth - margin * 2;
  const fmt = (v: number) => `Rs. ${v.toFixed(2)}`;

  /* Header */
  doc.setFontSize(18); doc.setFont('helvetica','bold'); doc.setTextColor(20,20,20);
  doc.text(user.shopName || 'Company Name', margin, 16);
  doc.setFontSize(9); doc.setFont('helvetica','normal');
  doc.text(user.address || '', margin, 22);
  doc.text(`${user.city||''}${user.city&&user.district?', ':''}${user.district||''}`, margin, 26);
  doc.text(`${user.state||''}${user.state&&user.mobile?' | ':''}Mobile: ${user.mobile||''}`, margin, 30);
  doc.text(`GSTIN: ${user.gstNo||'N/A'}`, margin, 34);

  doc.setFontSize(20); doc.setFont('helvetica','bold');
  doc.text('INVOICE', pageWidth-margin, 18, { align:'right' });
  doc.setFontSize(10); doc.setFont('helvetica','bold');
  doc.text('Bill No.', pageWidth-margin, 28, { align:'right' });
  doc.setFont('helvetica','normal');
  doc.text(`${bill.billNo}`, pageWidth-margin-10, 28, { align:'right' });
  doc.setFont('helvetica','bold');
  doc.text('Date', pageWidth-margin, 34, { align:'right' });
  doc.setFont('helvetica','normal');
  doc.text(new Date(bill.date).toLocaleDateString('en-IN'), pageWidth-margin-10, 34, { align:'right' });

  let y = 50;

  /* Customer */
  doc.setFontSize(10); doc.setFont('helvetica','bold'); doc.setTextColor(30,58,95);
  doc.text('Name', margin, y); doc.setFont('helvetica','normal'); doc.setTextColor(50,50,50);
  doc.line(margin+18, y+1, pageWidth-margin, y+1);
  doc.text(bill.customerName||'-', margin+20, y);
  y += 8;
  doc.setFont('helvetica','bold'); doc.setTextColor(30,58,95);
  doc.text('Address', margin, y); doc.setFont('helvetica','normal'); doc.setTextColor(50,50,50);
  doc.line(margin+22, y+1, pageWidth-margin, y+1);
  doc.text(bill.customerAddress||'-', margin+24, y);
  y += 8;
  doc.setFont('helvetica','bold'); doc.setTextColor(30,58,95);
  doc.text('Phone No.', margin+80, y); doc.setFont('helvetica','normal');
  doc.line(margin+105, y+1, pageWidth-margin, y+1);
  doc.text(bill.customerPhone||'-', margin+107, y);
  y += 10;

  /* Items Table */
  autoTable(doc, {
    head: [['SL.NO.','DESCRIPTION','HSN','QTY','RATE','AMOUNT']],
    body: bill.items.map((item, i) => [
      String(i+1), item.name, item.hsn||'-',
      `${item.quantity} ${item.unit}`, fmt(item.rate), fmt(item.amount),
    ]),
    startY: y,
    margin: { left: margin, right: margin },
    tableWidth: contentWidth,
    styles: { fontSize:9, textColor:[50,50,50], overflow:'linebreak', cellPadding:3 },
    headStyles: { fillColor:[30,58,95], textColor:[255,255,255], fontSize:9, fontStyle:'bold', halign:'center' },
    alternateRowStyles: { fillColor:[240,248,255] },
    columnStyles: {
      0: { halign:'center', cellWidth:12 },
      1: { cellWidth:70, halign:'left' },
      2: { halign:'center', cellWidth:22 },
      3: { halign:'center', cellWidth:25 },
      4: { halign:'right', cellWidth:30 },
      5: { halign:'right', cellWidth:36 },
    },
    theme: 'grid',
  });

  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 5;
  let ty = finalY;
  const tx = pageWidth - margin - 75;

  doc.setFontSize(10); doc.setFont('helvetica','bold'); doc.setTextColor(30,58,95);
  doc.text('Sub Total', tx, ty); doc.setFont('helvetica','normal');
  doc.text(fmt(bill.subTotal), pageWidth-margin-5, ty, { align:'right' });
  ty += 7;
  doc.setFont('helvetica','bold');
  doc.text(`CGST ${bill.cgstPercent}%`, tx, ty); doc.setFont('helvetica','normal');
  doc.text(fmt(bill.cgstAmount), pageWidth-margin-5, ty, { align:'right' });
  ty += 7;
  doc.setFont('helvetica','bold');
  doc.text(`SGST ${bill.sgstPercent}%`, tx, ty); doc.setFont('helvetica','normal');
  doc.text(fmt(bill.sgstAmount), pageWidth-margin-5, ty, { align:'right' });
  ty += 8;
  doc.setDrawColor(200,200,200); doc.setLineWidth(0.1);
  doc.line(tx-5, ty-3, pageWidth-margin, ty-3);
  doc.setTextColor(30,58,95); doc.setFont('helvetica','bold');
  doc.text('Grand Total', tx, ty);
  doc.text(fmt(bill.grandTotal), pageWidth-margin-5, ty, { align:'right' });
  ty += 12;

  doc.setFontSize(9); doc.setFont('helvetica','bold'); doc.setTextColor(30,58,95);
  doc.text(`GSTIN: ${user.gstNo||'N/A'}`, margin, ty);
  ty += 7;
  doc.setFont('helvetica','italic'); doc.setTextColor(80,80,80);
  doc.text(`Rupees in words: ${numberToWords(bill.grandTotal)}`, margin, ty);
  ty += 15;
  doc.setFont('helvetica','normal'); doc.setTextColor(30,58,95);
  doc.text('Signature', pageWidth-margin-5, ty, { align:'right' });
  doc.line(pageWidth-margin-50, ty-5, pageWidth-margin, ty-5);

  doc.setFontSize(7); doc.setTextColor(150,150,150);
  doc.text('Generated by BillCraft — Made with ❤ by Shela Gang', pageWidth/2, 290, { align:'center' });

  doc.save(`Invoice_${bill.billNo}_${new Date(bill.date).toLocaleDateString('en-IN').replace(/\//g,'-')}.pdf`);
}
